import Head from 'next/head'
const Header = () => {
  return (
    <Head>
      <title>Note Taking App.</title>
      <meta name="Init description." content="Generated by Create Next App." />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadSection